apiVersion: v1
kind: Pod
metadata:
  name: "debian"
  namespace: default
  labels:
    app: "debian"
spec:
  containers:
    - name: debian
      image: "debian:latest"
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
      command: ["tail", "-f", "/dev/null"]
  restartPolicy: Always
