apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 3
  template:
    metadata:
      name: "hello-app"
      labels:
        app: "hello-app"
    spec:
      containers:
        - name: hello-app
          image: "matiruizsh1/hello-app:v0.2"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: HELLO
              value: WORLD
          ports:
            - containerPort: 3000
              name: hello-app
      restartPolicy: Always
