apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: default
spec:
  selector:
    app: hello-app
  type: ClusterIP
  ports:
    - name: hello-app
      protocol: TCP
      port: 80
      targetPort: 3000
